# Generated by Django 4.2 on 2023-05-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200, verbose_name='Keywords to be Scraped')),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
            },
        ),
        migrations.CreateModel(
            name='ScrapedTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('price', models.FloatField(verbose_name='Price')),
                ('rating', models.FloatField(verbose_name='Rating')),
                ('asin', models.CharField(max_length=10, verbose_name='ASIN')),
                ('page_number', models.IntegerField(verbose_name='Page Number')),
                ('search_result_position', models.IntegerField(verbose_name='Search Result Position')),
                ('is_sponsored', models.BooleanField(verbose_name='Is Product Sponsored')),
                ('keyword', models.CharField(max_length=200, verbose_name='Keywords to be Scraped')),
                ('date_time_scraped', models.DateTimeField(verbose_name='Date and Time of Scraping')),
            ],
        ),
        migrations.CreateModel(
            name='ScraperStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scraper_status', models.CharField(max_length=200, verbose_name='Scraper Status')),
                ('scraper_last_ran', models.DateTimeField(verbose_name='Log Time')),
            ],
            options={
                'verbose_name': 'Scraper Status',
                'verbose_name_plural': 'Scraper Status',
            },
        ),
    ]
